# example configuration file with snake_case keys
owner: Bob TBeam
owner_short: BOB

channel_url: https://www.meshtastic.org/e/#CgMSAQESCDgBQANIAVAe

canned_messages: Hi|Bye|Yes|No|Ok
ringtone: 24:d=32,o=5,b=565:f6,p,f6,4p,p,f6,p,f6,2p,p,b6,p,b6,p,b6,p,b6,p,b,p,b,p,b,p,b,p,b,p,b,p,b,p,b,1p.,2p.,p

location:
  lat: 35.88888
  lon: -93.88888
  alt: 304

config:
  bluetooth:
    enabled: true
    fixed_pin: 123456
  device:
    serial_enabled: true
  display:
    screen_on_secs: 600
  lora:
    region: US
    hop_limit: 3
    tx_enabled: true
    tx_power: 30
  network:
    ntp_server: 0.pool.ntp.org
  position:
    gps_attempt_time: 900
    gps_enabled: true
    gps_update_interval: 120
    position_broadcast_secs: 900
    position_broadcast_smart_enabled: true
    position_flags: 3
  power:
    wait_bluetooth_secs: 60
    ls_secs: 300
    min_wake_secs: 10
    sds_secs: 4294967295

module_config:
  telemetry:
    device_update_interval: 900
    environment_update_interval: 900
