"""Backwards compatibility layer for BLE interface."""

# Import the new modular structure and expose it through the old interface
from meshtastic.interfaces.ble import *

# Ensure all the expected classes and functions are available
__all__ = [
    "BLEConfig",
    "ConnectionState",
    "BLEStateManager",
    "ThreadCoordinator",
    "BLEErrorHandler",
    "ReconnectPolicy",
    "RetryPolicy",
    "BLEClient",
    "DiscoveryStrategy",
    "ConnectedStrategy",
    "DiscoveryManager",
    "ConnectionValidator",
    "ClientManager",
    "ConnectionOrchestrator",
    "ReconnectScheduler",
    "ReconnectWorker",
    "NotificationManager",
    "BLEInterface",
    # Constants
    "SERVICE_UUID",
    "TORADIO_UUID",
    "FROMRADIO_UUID",
    "FROMNUM_UUID",
    "LEGACY_LOGRADIO_UUID",
    "LOGRADIO_UUID",
    "MALFORMED_NOTIFICATION_THRESHOLD",
    "DISCONNECT_TIMEOUT_SECONDS",
    "RECEIVE_THREAD_JOIN_TIMEOUT",
    "EVENT_THREAD_JOIN_TIMEOUT",
    "BLE_SCAN_TIMEOUT",
    "RECEIVE_WAIT_TIMEOUT",
    "EMPTY_READ_RETRY_DELAY",
    "EMPTY_READ_MAX_RETRIES",
    "TRANSIENT_READ_MAX_RETRIES",
    "TRANSIENT_READ_RETRY_DELAY",
    "SEND_PROPAGATION_DELAY",
    "GATT_IO_TIMEOUT",
    "NOTIFICATION_START_TIMEOUT",
    "CONNECTION_TIMEOUT",
    "EMPTY_READ_WARNING_COOLDOWN",
    "AUTO_RECONNECT_INITIAL_DELAY",
    "AUTO_RECONNECT_MAX_DELAY",
    "AUTO_RECONNECT_BACKOFF",
    "AUTO_RECONNECT_JITTER_RATIO",
    "BLEAK_CONNECTED_DEVICE_FALLBACK_MIN_VERSION",
    "BLECLIENT_EVENT_THREAD_JOIN_TIMEOUT",
    # Error messages
    "ERROR_TIMEOUT",
    "ERROR_MULTIPLE_DEVICES",
    "ERROR_READING_BLE",
    "ERROR_NO_PERIPHERAL_FOUND",
    "ERROR_WRITING_BLE",
    "ERROR_CONNECTION_FAILED",
    "ERROR_NO_PERIPHERALS_FOUND",
    "BLECLIENT_ERROR_ASYNC_TIMEOUT",
    # Utility functions
    "_sleep",
    "_parse_version_triplet",
    "_bleak_supports_connected_fallback",
    "logger",
]